version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: placement_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server   # Make sure your Node.js code is in a folder named 'server'
    container_name: placement_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/placementDB
    depends_on:
      - mongodb

  frontend:
    build: ./client   # Make sure your React code is in a folder named 'client'
    container_name: placement_frontend
    ports:
      - "3000:3000"
    stdin_open: true  
    depends_on:
      - backend

volumes:
  mongo_data: